### ISSUE TITLE
Authorization header : comma separated, POST : content-type

### ISSUE THREAD

**Issue by sylvainvivien** [mikeknapp/AppEngine-OAuth-Library#1]
Hi,
I think, there is an issue with the consumer request parameters and particularly the Authorization header. http://oauth.net/core/1.0/#consumer_req_param

Authorization Header : Parameters are separated by a comma character.
Example : Authorization: OAuth realm="http://sp.example.com/",oauth_consumer_key="0685bd9184jfhq22",oauth_token="ad180jjd733klru7",.......

If sent with an HTTP POST the content-type should be application/x-www-form-urlencoded

Regards

Sylvain

**Comment by mikeknapp** [comment]
Does this produce an error on any service, such as Twitter? If so, we'll fix it. Otherwise I don't really care that much. 

Thanks for reporting though. :)

**Comment by sylvainvivien** [comment]
Currently, no error ;)

**Comment by mikeknapp** [comment]
Okay - great thanks. I'll worry about it when it starts to break... unless you want to submit a patch that is. ;)

Thanks for spotting this. Great catch!
