### ISSUE TITLE
Setting Content-Type

### ISSUE THREAD

**Issue by phiali** [mikeknapp/AppEngine-OAuth-Library#2]
Hi,

This is a great library and I've got it working perfectly for use with Twitter. I've created a Google Latitude client with it, however one requirement when updating a users location is so have a Content-Type of application/json when POSTing.

As an initial stab I tried to add to the headers in make_async_request however that seems to throw off the authorisation and I get back a 401 response. Any idea on how to get this library to support setting this?

Thanks,
Alistair

**Comment by mikeknapp** [comment]
Hi Alistair

I'm not too sure exactly how to get this to work - and it's not something I have time to research and support properly. 

You're welcome though to branch the code and modify it as you see fit.

Best of luck with it. :)

Mike
