### ISSUE TITLE
no encoding of key used for HMAC-SHA1 signing

### ISSUE THREAD

**Issue by sethcall** [mikeknapp/AppEngine-OAuth-Library#3]
I believe that this line:

key = "%s&%s" % (self.consumer_secret, secret) # Note compulsory "&".

should read:

key =  urlencode({self.consumer_secret : secret}).replace("=", "&")

I'm basing this on this part of the specification:
http://oauth.net/core/1.0/#anchor16

However, I don't know how this would affect existing interoperability with Twitter, MySpace, etc.  But I do know it fixes interoperability issues with a server-side java library, http://spring-security-oauth.codehaus.org/, which does encode these values when constructing the key.

Perhaps it should be an option.

**Comment by mikeknapp** [comment]
Hi there

Thanks for reporting this. I'd be happy to review a patch if you'd like to submit one.

Best if it is optional, and turned off by default.

Cheers
Mike
