### ISSUE TITLE
Tilde Character in Twitter Status Update Causes "Incorrect Signature" Error

### ISSUE THREAD

**Issue by lassytouton** [mikeknapp/AppEngine-OAuth-Library#4]
If a twitter status update contains a tilde character then the status update will fail with an "incorrect signature" error.

This issue can be resolved by modifying the encode function as follows. Note that the encode function is nested in OAuthClient's prepare_request function (located in oauth.py).

Change

```
def encode(text):
  return urlquote(str(text), "")
```

to

```
def encode(text):
  return urlquote(str(text), "~")
```

**Comment by mikeknapp** [comment]
Cool - thanks. I've made this change now. Sorry for the delay!
